### PR TITLE
Bug 1770827 - Balrog pin

### PR DESCRIPTION
**Pull request by bytesized**
Adds support for update pinning to balrogscript

### CODE REVIEW

**Review by jcristau — CHANGES_REQUESTED** [review]
I think we need to add the new param to balrogscript/src/balrogscript/data/balrog_schedule_schema.json and balrogscript/src/balrogscript/data/balrog_submit-toplevel_schema.json, or validate_task_schema will break.

Looks good otherwise, thanks.

**Comment by bytesized** [comment]
Last push was a rebase.

**Review by gbrownmozilla — APPROVED** [review]
This looks good, and jcristau's request for schema update looks good now.

**Comment by bytesized** [comment]
Last push was a rebase.

**Review by jcristau — APPROVED** [review]

**Pull request merged**
