### PR TITLE
fix(beetmover): Bug 1910238 - GCS object rewrite missing info

### PR DESCRIPTION
**Pull request by hneiva**

### CODE REVIEW

**Review by jcristau — CHANGES_REQUESTED** [review]
Please also preserve cache_control.

**Comment by hneiva** [comment]
> Please also preserve cache_control.

Great idea!

Updated

**Review by jcristau — APPROVED** [review]
Thanks for adding to the test as well.

nit: consider updating the PR title and commit message before merging

**Comment by hneiva** [comment]
image
Managed to get the blob copied with the desired metadata in [staging](https://console.cloud.google.com/storage/browser/_details/moz-fx-productdelivery-no-7d6a-productdelivery/pub/firefox/releases/133.0b10/win64/en-US/Firefox%20Setup%20133.0b10.exe;tab=live_object?project=moz-fx-productdelivery-no-7d6a)

**Review by bhearsum — APPROVED** [review]

**Pull request merged**
