### PR TITLE
fix: Package pinning with backtracking

### LINKED ISSUE #990: Pinning packages is broken
`pip-compile-multi` uses the legacy resolver of pip by default, and is unable to find packages for some google packages.

For example: (error compiling beetmoverscript dependencies)
```
Using legacy resolver. Consider using backtracking resolver with `--resolver=backtracking`.
Could not find a version that matches protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,<6.0dev,>=3.19.0,>=3.19.5,>=5.26.1 (from google-cloud-artifact-registry==1.11.3->-r requirements/base.in (line 9))
Tried: 2.0.3, 2.3.0, 2.4.1, 2.5.0, 2.6.0, 2.6.1, 3.0.0, 3.0.0, 3.1.0, 3.1.0.post1, 3.1.0.post1, 3.2.0, 3.2.0, 3.3.0, 3.4.0, 3.4.0, 3.5.0.post1, 3.5.0.post1, 3.5.1, 3.5.1, 3.5.2, 3.5.2, 3.5.2.post1, 3.5.2.post1, 3.6.0, 3.6.0, 3.6.1, 3.6.1, 3.7.0, 3.7.0, 3.7.1, 3.7.1, 3.8.0, 3.8.0, 3.9.0, 3.9.0, 3.9.1, 3.9.1, 3.9.2, 3.9.2, 3.10.0, 3.10.0, 3.11.0, 3.11.0, 3.11.1, 3.11.1, 3.11.2, 3.11.2, 3.11.3, 3.11.3, 3.12.2, 3.12.2, 3.12.4, 3.12.4, 3.13.0, 3.13.0, 3.14.0, 3.14.0, 3.15.0, 3.15.0, 3.15.1, 3.15.1, 3.15.2, 3.15.2, 3.15.3, 3.15.3, 3.15.4, 3.15.4, 3.15.5, 3.15.5, 3.15.6, 3.15.6, 3.15.7, 3.15.7, 3.15.8, 3.15.8, 3.16.0, 3.16.0, 3.17.0, 3.17.0, 3.17.1, 3.17.1, 3.17.2, 3.17.2, 3.17.3, 3.17.3, 3.18.0, 3.18.0, 3.18.1, 3.18.1, 3.18.3, 3.18.3, 3.19.0, 3.19.0, 3.19.1, 3.19.1, 3.19.2, 3.19.2, 3.19.3, 3.19.3, 3.19.4, 3.19.4, 3.19.5, 3.19.5, 3.19.6, 3.19.6, 3.20.0, 3.20.0, 3.20.1, 3.20.1, 3.20.2, 3.20.2, 3.20.3, 3.20.3, 4.21.0, 4.21.0, 4.21.0, 4.21.0, 4.21.1, 4.21.1, 4.21.1, 4.21.1, 4.21.2, 4.21.2, 4.21.2, 4.21.2, 4.21.3, 4.21.3, 4.21.3, 4.21.3, 4.21.4, 4.21.4, 4.21.4, 4.21.4, 4.21.5, 4.21.5, 4.21.5, 4.21.5, 4.21.6, 4.21.6, 4.21.6, 4.21.6, 4.21.7, 4.21.7, 4.21.7, 4.21.7, 4.21.8, 4.21.8, 4.21.8, 4.21.8, 4.21.9, 4.21.9, 4.21.9, 4.21.9, 4.21.10, 4.21.10, 4.21.10, 4.21.10, 4.21.11, 4.21.11, 4.21.11, 4.21.11, 4.21.12, 4.21.12, 4.21.12, 4.21.12, 4.22.0, 4.22.0, 4.22.0, 4.22.1, 4.22.1, 4.22.1, 4.22.3, 4.22.3, 4.22.3, 4.22.4, 4.22.4, 4.22.4, 4.22.5, 4.22.5, 4.22.5, 4.23.0, 4.23.0, 4.23.0, 4.23.1, 4.23.1, 4.23.1, 4.23.2, 4.23.2, 4.23.2, 4.23.3, 4.23.3, 4.23.3, 4.23.4, 4.23.4, 4.23.4, 4.24.0, 4.24.0, 4.24.0, 4.24.1, 4.24.1, 4.24.1, 4.24.2, 4.24.2, 4.24.2, 4.24.3, 4.24.3, 4.24.3, 4.24.4, 4.24.4, 4.24.4, 4.25.0, 4.25.0, 4.25.0, 4.25.1, 4.25.1, 4.25.1, 4.25.2, 4.25.2, 4.25.2, 4.25.3, 4.25.3, 4.25.3, 5.26.0, 5.26.0, 5.26.0, 5.26.1, 5.26.1, 5.26.1
Skipped pre-versions: 2.0.0b0, 3.0.0a2, 3.0.0a3, 3.0.0b1, 3.0.0b1.post1, 3.0.0b1.post2, 3.0.0b2, 3.0.0b2, 3.0.0b2.post1, 3.0.0b2.post1, 3.0.0b2.post2, 3.0.0b2.post2, 3.0.0b3, 3.0.0b4, 3.0.0b4, 3.2.0rc1, 3.2.0rc1, 3.2.0rc1.post1, 3.2.0rc1.post1, 3.2.0rc2, 3.2.0rc2, 3.7.0rc2, 3.7.0rc2, 3.7.0rc3, 3.7.0rc3, 3.8.0rc1, 3.8.0rc1, 3.9.0rc1, 3.9.0rc1, 3.10.0rc1, 3.10.0rc1, 3.11.0rc1, 3.11.0rc1, 3.11.0rc2, 3.11.0rc2, 3.13.0rc3, 3.13.0rc3, 3.14.0rc1, 3.14.0rc1, 3.14.0rc2, 3.14.0rc2, 3.14.0rc3, 3.14.0rc3, 3.15.0rc1, 3.15.0rc1, 3.15.0rc2, 3.15.0rc2, 3.16.0rc1, 3.16.0rc1, 3.16.0rc2, 3.16.0rc2, 3.17.0rc1, 3.17.0rc1, 3.17.0rc2, 3.17.0rc2, 3.18.0rc1, 3.18.0rc1, 3.18.0rc2, 3.18.0rc2, 3.19.0rc1, 3.19.0rc1, 3.19.0rc2, 3.19.0rc2, 3.20.0rc1, 3.20.0rc1, 3.20.0rc2, 3.20.0rc2, 3.20.1rc1, 3.20.1rc1, 4.0.0rc1, 4.0.0rc1, 4.0.0rc2, 4.0.0rc2, 4.21.0rc1, 4.21.0rc1, 4.21.0rc1, 4.21.0rc1, 4.21.0rc2, 4.21.0rc2, 4.21.0rc2, 4.21.0rc2, 4.22.0rc2, 4.22.0rc2, 4.22.0rc2, 4.22.0rc3, 4.22.0rc3, 4.22.0rc3, 4.23.0rc2, 4.23.0rc2, 4.23.0rc2, 4.23.0rc3, 4.23.0rc3, 4.23.0rc3, 4.24.0rc1, 4.24.0rc1, 4.24.0rc1, 4.24.0rc2, 4.24.0rc2, 4.24.0rc2, 4.24.0rc3, 4.24.0rc3, 4.24.0rc3, 4.25.0rc1, 4.25.0rc1, 4.25.0rc1, 4.25.0rc2, 4.25.0rc2, 4.25.0rc2, 5.26.0rc1, 5.26.0rc1, 5.26.0rc1, 5.26.0rc2, 5.26.0rc2, 5.26.0rc2, 5.26.0rc3, 5.26.0rc3, 5.26.0rc3, 5.27.0rc1, 5.27.0rc1, 5.27.0rc1, 5.27.0rc2, 5.27.0rc2, 5.27.0rc2
There are incompatible versions in the resolved dependencies:
  protobuf<6.0dev,>=5.26.1 (from grpcio-status==1.63.0->google-api-core[grpc]==2.19.0->google-cloud-storage==2.16.0->-r requirements/base.in (line 8))
  protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5 (from google-cloud-artifact-registry==1.11.3->-r requirements/base.in (line 9))
  protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0.dev0,>=3.19.5 (from google-api-core[grpc]==2.19.0->google-cloud-storage==2.16.0->-r requirements/base.in (line 8))
  protobuf!=3.20.0,!=3.20.1,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0.dev0,>=3.19.5 (from googleapis-common-protos[grpc]==1.63.0->google-api-core[grpc]==2.19.0->google-cloud-storage==2.16.0->-r requirements/base.in (line 8))
  protobuf!=3.20.0,!=3.20.1,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5 (from grpc-google-iam-v1==0.13.0->google-cloud-artifact-registry==1.11.3->-r requirements/base.in (line 9))
  protobuf<5.0.0dev,>=3.19.0 (from proto-plus==1.23.0->google-cloud-artifact-registry==1.11.3->-r requirements/base.in (line 9))
```

### PR DESCRIPTION
**Pull request by hneiva**
Solves a current problem resolving dependencies with google packages. ie: in beetmoverscript and google-cloud-{storage,artifact-registry}

Fixes #990

### CODE REVIEW

**Review by bhearsum — APPROVED** [review]

**Review by jcristau — CHANGES_REQUESTED** [review]
Can you describe the current problem this solves in the commit message (i.e. include the actual error message, not just a vague reference)?

**Comment by hneiva** [comment]
Added the info in the commit and added an issue with the same info

**Review by jcristau — APPROVED** [review]
I see major version bumps in taskcluster, mozilla-version.  Presumably we're ok with these?

**Comment by hneiva** [comment]
Looks like mozilla-version dropped support for python<3.8 (which is fine), and most major changes to taskcluster have to do with workers (we're only upgrading on iscript/notarization_poller - should be safe)

**Pull request merged**
