### PR TITLE
[pushmsixscript] allow 0 scopes in schema

### LINKED ISSUE #523: [pushmsixscript] Failure in staging: "jsonschema.exceptions.ValidationError: [] is too short"
https://firefox-ci-tc.services.mozilla.com/tasks/EQNZVH-JSe2AFXePz1Rhvw/runs/0/logs/public/logs/live_backing.log
```
Traceback (most recent call last):
  File "/app/bin/pushmsixscript", line 8, in <module>
    sys.exit(main())
  File "/app/lib/python3.9/site-packages/pushmsixscript/script.py", line 44, in main
    return client.sync_main(async_main, config_path=config_path, default_config=get_default_config())
  File "/app/lib/python3.9/site-packages/scriptworker_client/client.py", line 125, in sync_main
    verify_task_schema(config, task)
  File "/app/lib/python3.9/site-packages/scriptworker_client/client.py", line 86, in verify_task_schema
    verify_json_schema(task, task_schema)
  File "/app/lib/python3.9/site-packages/scriptworker_client/client.py", line 59, in verify_json_schema
    raise TaskVerificationError(
scriptworker_client.exceptions.TaskVerificationError: Can't verify task schema!
[] is too short
Failed validating 'minItems' in schema['properties']['scopes']:
    {'items': {'type': 'string'},
     'minItems': 1,
     'type': 'array',
     'uniqueItems': True}
On instance['scopes']:
    []
exit code: 1
```

### PR DESCRIPTION
**Pull request by gbrownmozilla**
Closes #523

### CODE REVIEW

**Comment by gbrownmozilla** [comment]
Same as https://github.com/mozilla-releng/scriptworker-scripts/blob/master/pushflatpakscript/src/pushflatpakscript/data/push_flatpak_task_schema.json#L13-L19

**Review by JohanLorenzo — APPROVED** [review]
This change makes sense to me! I remember we used to define scopes even for level 1 scriptworkers. Out of curiosity, would it make sense to create a scope for the `pushmsixscript` dev instances? In any case, I think it's fine to allow no scopes to be defined at the moment thanks to this safeguard[1] ➡️ no binary will be pushed anywhere if the corresponding scope isn't provided.

[1] https://github.com/mozilla-releng/scriptworker-scripts/blob/7ad649c58fdee53987fbfc8e260f6a1bfa520a8f/pushmsixscript/src/pushmsixscript/task.py#L16-L17

**Comment by gbrownmozilla** [comment]
Maybe? I'm not aware of the history, and trying to make pushmsix's config similar to that of other scriptworker-scripts.

**Comment by JohanLorenzo** [comment]
Sounds good! Thank you for the context 🙂

**Pull request merged**
