### PR TITLE
bug 1728330 - Delete pushsnap

### PR DESCRIPTION
**Pull request by escapewindow**

### CODE REVIEW

**Review by bhearsum — APPROVED** [review]
We should probably cleanup `cloudops-infra` and the associated sops repo, too.

**Comment by escapewindow** [comment]
Blocked on esr78 EOL.

**Comment by jmaher** [comment]
I think we can merge this now?

**Comment by escapewindow** [comment]
Let's land https://github.com/mozilla-services/cloudops-infra/pull/3525 first, so we don't deploy any new pushsnap k8s pools; then we can clean up code and configs at will.

**Pull request merged**
