### PR TITLE
Re-land treescript fixes from #9

### PR DESCRIPTION
**Pull request by escapewindow**
We backed these out for GCP automation expediency; let's rebase, fix, reland.

### CODE REVIEW

**Comment by escapewindow** [comment]
@Callek I'm trying to re-land #9 in the new GCP world.

- I had to change the docker creation steps to allow for installing `../scriptworker_client` before `treescript`
- I'm hardcoding the treestatus url for now
- I made attempts to pick up fixes that landed after #9, both in scriptworker-scripts and in treescript. I think I've got them all.

Tests pass (the graph is green, after I reran the failing docker image task). I'd like to test in dev before we roll out, but I think the patchset is ready for review.

**Comment by escapewindow** [comment]
Testing looks good on treescriptworker-dev1, which I spun up to test. Still want to test in docker dev.

**Comment by escapewindow** [comment]
> sheehan 12:30
aki: I haven't seen that before but I took a look and I think it's a bug in robustcheckout
purge used to import util when that line was introduced, now imports scmutil and cmdutil instead

**Comment by escapewindow** [comment]
- [green tagging task](https://firefox-ci-tc.services.mozilla.com/tasks/UXSVmmlPRxO20oebPfWk6A)
- [green l10n bump task](https://firefox-ci-tc.services.mozilla.com/tasks/P0IXyMGRQNSgERrmQ2NHcw)

**Review by Callek — APPROVED** [review]

**Pull request merged**
