### PR TITLE
chore(deps): Update pinned dependencies

### PR DESCRIPTION
**Pull request by hneiva**

### CODE REVIEW

**Review by bhearsum — APPROVED** [review]
`simple-github` is a major bump, but it looks like only for a change to `client.request` which appears to be unused here.

`taskcluster` is a major bump, but only because the services have caused it AFAICT.

No other major bumps.

**Review by ahal — CHANGES_REQUESTED** [review]
Hang on, the `simple-github` bump almost for sure needs some code changes.

**Review by ahal — APPROVED** [review]
Oh sorry, you're right. I forgot treescript only uses the GraphQL endpoint. I wanted to do a quick r- just in case Heitor was about to merge it.

**Comment by hneiva** [comment]
Thanks for double checking! :)

**Pull request merged**
