### PR TITLE
Drop Python 3.6, use 3.8 instead

### PR DESCRIPTION
**Pull request by rail**

### CODE REVIEW

**Comment by escapewindow** [comment]
<s>We may want to run our unit tests on py38 before we run it in production :)</s>

Ah, you're adding 3.8, but running on 3.7. n/m :)

**Comment by rail** [comment]
Time to rebase

**Comment by MihaiTabara** [comment]
\o/

**Review by escapewindow — APPROVED** [review]
We could add the py37 and py38 support strings into setup.py, but that might not be necessary since we're not pushing these to pypi.

Looks good, 🚢 
Thanks!

**Pull request merged**
