### PR TITLE
Explicitly set `taskcluster_root_url`

### PR DESCRIPTION
**Pull request by rail**
This depends on https://github.com/mozilla-services/cloudops-infra/pull/1517

### CODE REVIEW

**Review by tomprince — APPROVED** [review]
I'm not familiar with the automation here, but this looks sensible and matches up with the cloudops-infra changes.

**Comment by MihaiTabara** [comment]
Just to confirm, for production, we'll have to corelate this change with another scriptworker release (similarly to https://github.com/MihaiTabara/scriptworker/releases/tag/27.0.1 shipped from https://github.com/MihaiTabara/scriptworker/commit/341c60fcc2406a8150dc65e3f9b9e8b89081b0b0) to patch things up.

**Comment by tomprince** [comment]
> Just to confirm, for production, we'll have to corelate this change with another scriptworker release (similarly to https://github.com/MihaiTabara/scriptworker/releases/tag/27.0.1 shipped from [MihaiTabara/scriptworker@341c60f](https://github.com/MihaiTabara/scriptworker/commit/341c60fcc2406a8150dc65e3f9b9e8b89081b0b0)) to patch things up.

I don't *think* so. [This](https://github.com/MihaiTabara/scriptworker/commit/341c60fcc2406a8150dc65e3f9b9e8b89081b0b0#diff-4f43b126671fd39d1f9e922fbb72b839R33) line has the same effect as this pull request does, and the other two changes are to CLI tools that won't be used in production (in any case, they default to the environment variable, which will be set in the containers).

**Comment by rail** [comment]
> Just to confirm, for production, we'll have to corelate this change with another scriptworker release (similarly to https://github.com/MihaiTabara/scriptworker/releases/tag/27.0.1 shipped from [MihaiTabara/scriptworker@341c60f](https://github.com/MihaiTabara/scriptworker/commit/341c60fcc2406a8150dc65e3f9b9e8b89081b0b0)) to patch things up.

Nah, we generate our own config and explicitly set the root URL, no need for defaults to change.

**Pull request merged**
