### PR TITLE
Add better support for `browser_specific_settings` (with `applications` as fallback)

### PR DESCRIPTION
**Pull request by willdurand**
Fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1810985

### CODE REVIEW

**Comment by willdurand** [comment]
(I am looking into the test failures between meetings..)

**Comment by willdurand** [comment]
@jcristau green 😎

**Review by jcristau — APPROVED** [review]
Thanks Will!

**Comment by jcristau** [comment]
A couple of notes:
- we may want to duplicate addonscript/tests/fake_target.langpack.xpi to use the modern key (or just update it)
- the beetmoverscript case looks like it's not covered?

**Comment by willdurand** [comment]
I added coverage for `addonscript` and I am trying to add new tests for `beetmoverscript`

**Comment by willdurand** [comment]
The new tests should pass now :)

**Pull request merged**
