### PR TITLE
Update robustcheckout

### PR DESCRIPTION
**Pull request by tomprince**

### CODE REVIEW

**Comment by tomprince** [comment]
This is currently untested. The mercurial in the treescript image is buster, which [has](https://hg.mozilla.org/hgcustom/version-control-tools/file/tip/hgext/robustcheckout/__init__.py) mercurial 4.8.2.

**Comment by tomprince** [comment]
It looks like the black failures are due to https://github.com/shopkeep/pytest-black/pull/37. That has been open since July.

**Comment by escapewindow** [comment]
It looks like adding the file inside the parens works: https://github.com/mozilla-releng/scriptworker-scripts/pull/111/commits/9aa5d4154924877d9d3983dba67e3e267e433bb5

**Comment by escapewindow** [comment]
[Busted l10n-bumper](https://firefox-ci-tc.services.mozilla.com/tasks/ZC-sf5E1TPORLJUF0xb94w/runs/0/logs/https%3A%2F%2Ffirefox-ci-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FZC-sf5E1TPORLJUF0xb94w%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive_backing.log):

```
2019-12-06 23:43:51,799 - scriptworker_client.utils - INFO -   File "/usr/lib/python2.7/dist-packages/mercurial/win32.py", line 23, in <module>
2019-12-06 23:43:51,799 - scriptworker_client.utils - INFO -     _kernel32 = ctypes.windll.kernel32
2019-12-06 23:43:51,799 - scriptworker_client.utils - INFO - AttributeError: 'module' object has no attribute 'windll'
```

**Comment by escapewindow** [comment]
https://firefox-ci-tc.services.mozilla.com/tasks/aG_Beao4Q9iu5u0G9OwWcA is a release-early-tagging task.

**Review by escapewindow — CHANGES_REQUESTED** [review]
Let's fix black and l10n-bumper. It's likely the same issue is going to hit the tagging/version bump tasks.

**Comment by tomprince** [comment]
> [Busted l10n-bumper](https://firefox-ci-tc.services.mozilla.com/tasks/ZC-sf5E1TPORLJUF0xb94w/runs/0/logs/https%3A%2F%2Ffirefox-ci-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FZC-sf5E1TPORLJUF0xb94w%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive_backing.log):
> 
> ```
> 2019-12-06 23:43:51,799 - scriptworker_client.utils - INFO -   File "/usr/lib/python2.7/dist-packages/mercurial/win32.py", line 23, in <module>
> 2019-12-06 23:43:51,799 - scriptworker_client.utils - INFO -     _kernel32 = ctypes.windll.kernel32
> 2019-12-06 23:43:51,799 - scriptworker_client.utils - INFO - AttributeError: 'module' object has no attribute 'windll'
> ```

https://bugzilla.mozilla.org/show_bug.cgi?id=1597746#c5

**Comment by tomprince** [comment]
It looks like #109 will fix the black error (by not using pytest-black).

**Comment by bhearsum** [comment]
> It looks like the black failures are due to [shopkeep/pytest-black#37](https://github.com/shopkeep/pytest-black/pull/37). That has been open since July.

FYI: We're not using `pytest-black` anymore after #109, we're running black on its own. So maybe this won't be an issue soon?

**Comment by escapewindow** [comment]
We need to push this to dev-treescript, and do two try pushes (after pointing at the -dev treescript workers).

- one `./mach try fuzzy --full`, and choose l10n-bumper
- one `./mach try release`, and trigger a staging release. Watch the release-early-tagging task

e.g. https://treeherder.mozilla.org/#/jobs?repo=try&revision=6964e52fafec519d7a85fc5565077f91bb9de99f and https://treeherder.mozilla.org/#/jobs?repo=try&revision=9ea0cfe88a6ff7fdd94adf8b89ea1c06a8926db6

**Comment by escapewindow** [comment]
Test pushes at https://treeherder.mozilla.org/#/jobs?repo=try&revision=cca88078d8b6ee541aeb5be0fcdef38cee6c6a2d and https://treeherder.mozilla.org/#/jobs?repo=try&revision=3810837ef65717979ed11bb30cb8a94b29ee52cc

**Review by escapewindow — APPROVED** [review]

**Pull request merged**
