### PR TITLE
Py38

### PR DESCRIPTION
**Pull request by escapewindow**
I'm kind of leaning towards always including the `pyVER` in the `requirements/*.txt` files. The patchset doesn't currently include that, but we could. One downside is we'd need to change the Dockerfile to point at the right `requirements/base.pyVER.txt` for 3.9, but we already have to modify that file.

I'm also happy to leave the PR as is. What do you think @rail ?

### CODE REVIEW

**Comment by escapewindow** [comment]
Maybe we leave the PR as is, and fix minor version upgrades in taskgraph.

**Comment by escapewindow** [comment]
I'm also not 100% sure about these patches, so we may want some staging runs. Or roll out at a quiet time when we can monitor and roll back.

**Review by rail — APPROVED** [review]
LGTM! Let's test it in staging! Also we can deploy the workers one by one in production.

**Review by bhearsum — APPROVED** [review]
I don't have strong feelings about always including the python version in the requirements files names - there's a good case to be made both ways. r+ either way :)

**Comment by escapewindow** [comment]
Thanks!

**Pull request merged**
