### PR TITLE
Bump scriptworker to 60.2.0

### PR DESCRIPTION
**Pull request by bhearsum**
Note this being done against `production` to avoid picking up any other changes with it. This means deploys will happen when it merges.

This bump was done with a local patch to ensure only scriptworker was picked up:
```
diff --git a/maintenance/pin-helper.sh b/maintenance/pin-helper.sh
index 7cc71ef2..ab3d6f7e 100755
--- a/maintenance/pin-helper.sh
+++ b/maintenance/pin-helper.sh
@@ -18,12 +18,12 @@ for dir in $DIRS; do
     if [ "$dir" = "pushflatpakscript" ]; then
         ARGS="$ARGS -g flat-manager"
     fi
     if [ "$dir" = "." ]; then
         ARGS="$EXTRA_ARGS -g test -g docs"
     fi
     echo $ARGS
     pushd "$dir"
-    pip-compile-multi --backtracking -u -o "$SUFFIX" $ARGS
+    pip-compile-multi --backtracking --upgrade-package scriptworker -o "$SUFFIX" $ARGS
     chmod 644 requirements/*.txt
     popd
 done
```

### CODE REVIEW

**Comment by bhearsum** [comment]
The ruff check is:
```
[task 2024-07-12T13:05:02.671Z] error: `ruff <path>` has been removed. Use `ruff check <path>` instead.
```

Which is pretty clearly unrelated.

**Review by jcristau — APPROVED** [review]
The base.in changes aren't required, I think?

**Comment by bhearsum** [comment]
> The base.in changes aren't required, I think?

Technically not I guess...

**Review by hneiva — APPROVED** [review]
LGTM

**Pull request merged**
