### PR TITLE
Bug 1868558 - Add new CoT keys as part of the Dec 2023 rotation

### PR DESCRIPTION
**Pull request by JohanLorenzo**
Depends on https://github.com/mozilla-releng/scriptworker/pull/629

### CODE REVIEW

**Comment by jcristau** [comment]
Why are we upgrading anything but scriptworker here?

**Comment by JohanLorenzo** [comment]
Sorry for the confusion. I will upgrade scriptworker in a separate commit after 49.1.0 is published.

**Comment by jcristau** [comment]
I understand that. I'm saying scriptworker is the only thing that needs to change in this PR.

**Comment by JohanLorenzo** [comment]
I totally agree. That's why I'm thinking of doing it in 2 steps. This way, we can revert everything but scriptworker.

**Comment by JohanLorenzo** [comment]
Discussed privately with @jcristau. I had forgotten we upgrade dependencies on Thursdays. Thus, I'll keep this PR to jump bumping scriptworker.

**Review by ahal — APPROVED** [review]

**Pull request merged**
