### PR TITLE
scriptworker 27.3.0 (and other deps)

### PR DESCRIPTION
**Pull request by escapewindow**

### CODE REVIEW

**Review by nthomas-mozilla — APPROVED** [review]

**Comment by escapewindow** [comment]
@MihaiTabara could we roll this out during the day? :) (avoiding rolling out in my evening)

**Comment by MihaiTabara** [comment]
Sorry, I missed this yesterday in my inbox. Taking care of this today, during my day.

**Comment by MihaiTabara** [comment]
Tracking this in https://tools.taskcluster.net/groups/KNM9qf2nSHmxmKiP4jVOtg

**Comment by MihaiTabara** [comment]
This is now completed.

**Pull request merged**
