### PR TITLE
[RELENG-430] add autograph_authenticode_sha2{,_stub} formats

### PR DESCRIPTION
**Pull request by escapewindow**
Depends on https://github.com/mozilla-services/cloudops-infra/pull/2951

I'll probably push to dev-signingscript when that lands, before merging this PR.

### CODE REVIEW

**Comment by escapewindow** [comment]
\o/ green staging run https://firefox-ci-tc.services.mozilla.com/tasks/GG2TvWsOSUe0J_byTTVKwg#artifacts

**Comment by escapewindow** [comment]
@bhearsum I wasn't sure if you're familiar with the k8s env vars + signingscript? I can flag you for review if you are.

**Review by bhearsum — APPROVED** [review]
> @bhearsum I wasn't sure if you're familiar with the k8s env vars + signingscript? I can flag you for review if you are.

I'm familiar enough to r+ this!

**Comment by escapewindow** [comment]
Thanks!

**Pull request merged**
