### PR TITLE
Bug 1621066 - pushflatpakscript: change to xz compression from gzip

### PR DESCRIPTION
**Pull request by MaXeraph**
Supplement for changing compression in [run.me](https://phabricator.services.mozilla.com/D66696)

As discussed in [bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1621066)

### CODE REVIEW

**Comment by MaXeraph** [comment]
Looking over the log, I think that the CI is failing is due to the fix in [run.me](https://phabricator.services.mozilla.com/D66696) has not been committed. But please let me know if I made any mistakes.

**Comment by escapewindow** [comment]
The test bustage is probably because we're using `.gz` artifact paths in https://github.com/mozilla-releng/scriptworker-scripts/blob/master/pushflatpakscript/tests/test_artifacts.py#L11-L16 .

**Comment by MaXeraph** [comment]
> The test bustage is probably because we're using `.gz` artifact paths in https://github.com/mozilla-releng/scriptworker-scripts/blob/master/pushflatpakscript/tests/test_artifacts.py#L11-L16 .

Do you think I also need to change the tests as well ?

**Review by MihaiTabara — COMMENTED** [review]
LGTM overall, doing a closer look, I think we also need to update `test_script`

```
(pushflatpakscript) mtabara@mozspace:[docs]~/work/mozilla/clones/git/scriptworker-scripts/pushflatpakscript$ grep -R 'flatpak.tar.gz'  *
src/pushflatpakscript/artifacts.py:        condition=lambda artifact: artifact.endswith(".flatpak.tar.gz"),
tests/test_script.py:    monkeypatch.setattr(artifacts, "get_flatpak_file_path", lambda _: "/some/file.flatpak.tar.gz")
tests/test_script.py:        assert file_ == "/some/file.flatpak.tar.gz"
tests/test_artifacts.py:        (False, ({"taskId": ["/path/to/file.flatpak.tar.gz"]}, {}), "/path/to/file.flatpak.tar.gz"),
tests/test_artifacts.py:        (False, ({"taskId": ["/path/to/file.flatpak.tar.gz", "/some/other/file.txt"]}, {}), "/path/to/file.flatpak.tar.gz"),
tests/test_artifacts.py:        (False, ({"taskId": ["/path/to/file.flatpak.tar.gz"], "otherTaskId": "/some/other/file.txt"}, {}), "/path/to/file.flatpak.tar.gz"),
tests/test_artifacts.py:        (True, ({}, {"taskId": ["/path/to/file.flatpak.tar.gz"]}), None),
tests/test_artifacts.py:        (True, ({"taskId": ["/path/to/file.flatpak.tar.gz"], "otherTaskId": ["/some/other/file.flatpak.tar.gz"]}, {}), None),
```

**Review by MihaiTabara — APPROVED** [review]
LGTM! We can land this to production as soon as we the in-tree code from https://phabricator.services.mozilla.com/D66696 landed to `beta` as well.

Thanks again for your contribution!

**Comment by MaXeraph** [comment]
> LGTM! We can land this to production as soon as we the in-tree code from https://phabricator.services.mozilla.com/D66696 landed to `beta` as well.
> 
> Thanks again for your contribution!

No worries !! It's been super cool to contribute to Mozilla haha ! Looking forward to contribute more.

**Comment by MihaiTabara** [comment]
Deployed to production as the in-tree patch has been approved for beta uplift.

**Pull request merged**
